export const strings_en = {
    word_Username: 'Username',
    word_Password: 'Password',
    word_Login: 'Login',
    word_Logout: 'Logout',
    word_Transaction_Successful: 'Transaction Successful.',
    word_Transaction_number_is: 'Transaction number is ',
    word_No_Overdraft_access_Please_contact_Help: "No Overdraft access, Please contact Help.",
    word_Ok: "Ok",
    word_Payment_Information: "Payment Information",
    word_Insufficient_Balance_in_your_account: "Insufficient Balance in your account",
    word_Please_select_currency_to_transfer: "Please select the currency to transfer",
    word_Select: "Select",
    word_Receiver_Information: "Receiver Information",
    word_BIC_Code: "BIC Code",
    word_Bank_Name: "Bank Name",
    word_Amount: "Amount",
    word_Sender_Information: "Sender Information",
    word_Sender_Acc_Num: "Sender Acc Num",
    word_Sender_Name: "Sender Name",
    word_To_Bank: "To Bank",
    word_To_Person: "To Person",
    word_Transfer_Type: "Transfer Type",
    word_Date: "Date",
    word_Message_Code: "Message Code",
    word_Sender_Details: "Sender Details",
    word_Receiver_Details: "Receiver Details",
    word_Payment_Details: "Payment Details",
    word_Its_WEEKEND: "It's WEEKEND !!!",
    word_Unable_to_do_any_transactions_on_weekdays: "Unable to do any transactions on weekdays.....",
    word_PAYMENT: "PAYMENT",
    word_Change_APP_Language: "Change APP Language?",
    word_Please_select_APP_language: "Please select APP language",
    word_Dashboard: "Dashboard",
    word_Customers: "Customers",
    word_Transactions: "Transactions",
    word_Transaction: "Transaction",
    word_All_Customers_list: "All Customers list",
    word_Number: 'Number',
    word_Name: "Name",
    word_Balance: "Balance",
    word_Debited: "Debited",
    word_Total_Amount: "Total Amount",
    word_Top_5_Bank_Transactions: "Top 5 Bank Transactions",
    word_Top_5_Customer_Transactions: "Top 5 Customer Transactions",
    word_Enter_your_username: "Enter your username",
    word_Enter_your_password: "Enter your password",
    word_Logged_out_from_previous_session: "Logged out from previous session❓",
    word_LOGOUT: "LOGOUT",
    word_to_continue: " to continue ...❗",
    word_Employee_Name: "Employee",
    word_Sender_Acc_No: "Sender",
    word_Receiver_Acc_No: "Receiver",
    word_Transaction_ID: "ID",
    word_Transaction_Type: "Type",
    word_Transaction_Amount: "Amount",
    word_Transaction_Date: "Date",
    word_Bank_Code: "Bank Code",
    word_All_Transactions_list: "All Transactions list",
    word_Message_code: "Message Code",
}