export const strings_tel = {
    word_Username: 'వినియోగదారు పేరు',
    word_Password: 'పాస్వర్డ్',
    word_Login: 'ప్రవేశించండి',
    word_Logout: 'లాగ్అవుట్',
    word_Transaction_Successful: 'లావాదేవీ విజయవంతమైంది.',
    word_Transaction_number_is: 'లావాదేవీ సంఖ్య',
    word_No_Overdraft_access_Please_contact_Help: "ఓవర్‌డ్రాఫ్ట్ యాక్సెస్ లేదు, దయచేసి సహాయాన్ని సంప్రదించండి.",
    word_Ok: "అలాగే",
    word_Payment_Information: "చెల్లింపు సమాచారం",
    word_Insufficient_Balance_in_your_account: "మీ ఖాతాలో తగినంత బ్యాలెన్స్ లేదు",
    word_Please_select_currency_to_transfer: "దయచేసి బదిలీ చేయడానికి కరెన్సీని ఎంచుకోండి",
    word_Select: "ఎంచుకోండి",
    word_Receiver_Information: "రిసీవర్ సమాచారం",
    word_BIC_Code: "BIC కోడ్",
    word_Bank_Name: "బ్యాంక్ పేరు",
    word_Amount: "మొత్తం",
    word_Sender_Information: "పంపినవారి సమాచారం",
    word_Sender_Acc_Num: "పంపినవారి సంఖ్య",
    word_Sender_Name: "పంపిన వారి పేరు",
    word_To_Bank: "బ్యాంకుకు",
    word_To_Person: "వ్యక్తికి",
    word_Transfer_Type: "బదిలీ రకం",
    word_Date: "తేదీ",
    word_Message_Code: "సందేశం కోడ్",
    word_Sender_Details: "పంపినవారి వివరాలు",
    word_Receiver_Details: "రిసీవర్ వివరాలు",
    word_Payment_Details: "చెల్లింపు వివరాలు",
    word_Its_WEEKEND: "ఇది వారాంతం !!!",
    word_Unable_to_do_any_transactions_on_weekdays: "వారం రోజుల్లో ఎలాంటి లావాదేవీలు చేయలేక.....",
    word_PAYMENT: "చెల్లింపు",
    word_Change_APP_Language: "APP భాషను మార్చాలా?",
    word_Please_select_APP_language: "దయచేసి APP భాషను ఎంచుకోండి",
    word_Dashboard: "డాష్బోర్డ్",
    word_Customers: "వినియోగదారులు",
    word_Transactions: "లావాదేవీలు",
    word_Transaction: "లావాదేవీ",
    word_All_Customers_list: "మొత్తం వినియోగదారుల జాబితా",
    word_Number: "సంఖ్య",
    word_Balance: "సంతులనం",
    word_Name: "పేరు",
    word_Debited: "డెబిట్ చేయబడింది",
    word_Total_Amount: "మొత్తం",
    word_Top_5_Bank_Transactions: "టాప్ 5 బ్యాంక్ లావాదేవీలు",
    word_Top_5_Customer_Transactions: "టాప్ 5 కస్టమర్ లావాదేవీలు",
    word_Enter_your_username: "మీ వినియోగదారు పేరును నమోదు చేయండి",
    word_Enter_your_password: "మీ పాస్వర్డ్ ని నమోదుచేయండి",
    word_Logged_out_from_previous_session: "మునుపటి సెషన్❓ నుండి లాగ్ అవుట్ చేయబడింది",
    word_LOGOUT: "లాగ్ అవుట్",
    word_to_continue: " కొనసాగించడానికి ...❗",
    word_Employee_Name: "ఉద్యోగి పేరు",
    word_Sender_Acc_No: "పంపినవారి ఖాతా సంఖ్య",
    word_Receiver_Acc_No: "రిసీవర్ ఖాతా సంఖ్య",
    word_Transaction_ID: "లావాదేవి ఐడి",
    word_Transaction_Type: "లావాదేవీ రకం",
    word_Transaction_Amount: "లావాదేవి మొత్తం",
    word_Transaction_Date: "లావాదేవీ తేదీ",
    word_Bank_Code: "బ్యాంక్ కోడ్",
    word_All_Transactions_list: "అన్ని లావాదేవీల జాబితా",
}