export const strings_hi = {
    word_Username: 'उपयोगकर्ता नाम',
    word_Password: 'पासवर्ड',
    word_Login: 'लॉग इन करें',
    word_Logout: 'लॉग आउट',
    word_Transaction_Successful: '',
    word_Transaction_number_is: 'लेन-देन सफल ।',
    word_No_Overdraft_access_Please_contact_Help: "कोई ओवरड्राफ्ट एक्सेस नहीं, कृपया सहायता से संपर्क करें।",
    word_Ok: "ठीक",
    word_Payment_Information: "भुगतान की जानकारी",
    word_Insufficient_Balance_in_your_account: "आपके खाते में अपर्याप्त शेष राशि",
    word_Please_select_currency_to_transfer: "कृपया स्थानांतरित करने के लिए मुद्रा का चयन करें",
    word_Select: "चुनना",
    word_Receiver_Information: "रिसीवर सूचना",
    word_BIC_Code: "BIC कोड",
    word_Bank_Name: "बैंक का नाम",
    word_Amount: "राशि",
    word_Sender_Information: "प्रेषक सूचना",
    word_Sender_Acc_Num: "प्रेषक खाता संख्या",
    word_Sender_Name: "भेजने वाले का नाम",
    word_To_Bank: "बैंक के लिए",
    word_To_Person: "व्यक्ति के लिए",
    word_Transfer_Type: "स्थानांतरण प्रकार",
    word_Date: "दिनांक",
    word_Message_Code: "संदेश कोड",
    word_Sender_Details: "विवरण भेजना",
    word_Receiver_Details: "रिसीवर विवरण",
    word_Payment_Details: "भुगतान विवरण",
    word_Its_WEEKEND: "यह सप्ताहांत है !!!",
    word_Unable_to_do_any_transactions_on_weekdays: "कार्यदिवसों पर कोई लेन-देन करने में असमर्थ.....",
    word_PAYMENT: "भुगतान",
    word_Change_APP_Language: "एपीपी भाषा बदलें?",
    word_Please_select_APP_language: "कृपया एपीपी भाषा चुनें",
    word_Dashboard: "डैशबोर्ड",
    word_Customers: "ग्राहकों",
    word_Transactions: "लेनदेन",
    word_Transaction: "लेन-देन",
    word_All_Customers_list: "सभी ग्राहक सूची",
    word_Number: 'संख्या',
    word_Balance: "संतुलन",
    word_Name: "नाम",
    word_Debited: "नामे किया",
    word_Total_Amount: "कुल राशि",
    word_Top_5_Bank_Transactions: "शीर्ष 5 बैंक लेनदेन",
    word_Top_5_Customer_Transactions: "शीर्ष 5 ग्राहक लेनदेन",
    word_Enter_your_username: "अपना उपयोगकर्ता नाम दर्ज करें",
    word_Enter_your_password: "अपना पासवर्ड डालें",
    word_Logged_out_from_previous_session: "पिछले सत्र से लॉग आउट",
    word_LOGOUT: "लॉग आउट",
    word_to_continue: " जारी रखने के लिए ...❗",
    word_Employee_Name: "कर्मचारी",
    word_Sender_Acc_No: "प्रेषक",
    word_Receiver_Acc_No: "प्राप्तकर्ता",
    word_Transaction_ID: "आईडी",
    word_Transaction_Type: "प्रकार",
    word_Transaction_Amount: "राशि",
    word_Transaction_Date: "तिथि",
    word_Bank_Code: "बैंक कोड",
    word_All_Transactions_list: "सभी लेनदेन सूची",
    word_Message_code: "संदेश कोड",
    word_Employee_ID: "कर्मचारी ID",
    word_Employee_Password: "कर्मचारी पासवर्ड",
}